package app.nostalgex.schedule

import app.nostalgex.model.MediaItem
import app.nostalgex.model.MediaType
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/** Golden strings generated by running packDay from scripts/nostalgex-daily-manifest.js on the same fixture. */
class DayPackerTest {
    private val dayStart = 1_700_100_000L
    private val packer = DayPacker()

    private val pool: List<MediaItem> = buildList {
        listOf("Seinfeld", "Friends", "The Office").forEachIndexed { si, show ->
            for (e in 1..5) add(MediaItem("e$si$e", show, 22, MediaType.EPISODE))
        }
        listOf(
            "Alien", "Mockingjay Part 2", "Heat", "Mockingjay Part 1", "Deathly Hallows: Part 2",
            "Jaws", "Deathly Hallows: Part 1", "Rocky", "Kill Bill Vol 1", "Dune",
        ).forEachIndexed { mi, title ->
            add(MediaItem("m$mi", title, 95 + mi * 3, MediaType.MOVIE, addedAtEpochSec = if (mi % 4 == 0) 1_700_000_000L else 0L))
        }
    }

    private fun render(blocks: List<app.nostalgex.model.ScheduleBlock>) =
        blocks.joinToString(",") { "${it.item.id}@${it.startEpochSec - dayStart}-${it.endEpochSec - dayStart}" }

    @Test fun `plain channel day`() {
        val out = packer.pack(DayPackRequest(pool, dayStart, 20000, channelId = 1))
        assertEquals(
            "m8@0-7140,m3@7140-13380,m1@13380-19260,m5@19260-25860,m6@25860-32640,m4@32640-39060,m7@39060-46020,m2@46020-52080,m9@52080-59400,m0@59400-65100,e22@65100-66420,e25@66420-67740,e03@67740-69060,e01@69060-70380,e15@70380-71700,e13@71700-73020,e23@73020-74340,e21@74340-75660,e04@75660-76980,e05@76980-78300,e14@78300-79620,e12@79620-80940,e24@80940-82260,e02@82260-83580,e11@83580-84900,m7@84900-86400",
            render(out),
        )
    }

    @Test fun `premiere channel promotes recent additions`() {
        val out = packer.pack(DayPackRequest(pool, dayStart, 20000, channelId = 1, isPremiereChannel = true))
        assertEquals(
            "m3@0-6240,m1@6240-12120,m5@12120-18720,m7@18720-25680,m2@25680-31740,m6@31740-38520,m4@38520-44940,m9@44940-52260,e22@52260-53580,e25@53580-54900,e03@54900-56220,e01@56220-57540,e15@57540-58860,e13@58860-60180,e23@60180-61500,e21@61500-62820,e04@62820-64140,e05@64140-65460,e14@65460-66780,e12@66780-68100,e24@68100-69420,e02@69420-70740,e11@70740-72060,m0@72060-77760,m8@77760-84900,e11@84900-85180,m7@85180-86400",
            render(out),
        )
    }

    @Test fun `yesterday's aired titles are skipped and seam guard applies`() {
        val out = packer.pack(
            DayPackRequest(pool, dayStart, 20001, channelId = 49, yesterdayAired = setOf("m1", "m3", "e01"), yesterdayLastId = "m8"),
        )
        assertEquals(
            "m2@0-6060,m9@6060-13380,e24@13380-14700,e22@14700-16020,e04@16020-17340,e05@17340-18660,m6@18660-25440,m4@25440-31860,m0@31860-37560,m8@37560-44700,m7@44700-51660,e12@51660-52980,e14@52980-54300,m5@54300-60900,e23@60900-62220,e25@62220-63540,e02@63540-64860,e03@64860-66180,e13@66180-67500,e15@67500-68820,e21@68820-70140,e11@70140-71460,m8@71460-78189,m3@78189-84429,m1@84429-86400",
            render(out),
        )
    }

    @Test fun `short pool loops with golden-ratio offset and fills the day`() {
        val small = pool.take(5)
        val out = packer.pack(DayPackRequest(small, dayStart, 20002, channelId = 5, yesterdayLastId = "e01"))
        val text = render(out)
        assertTrue(text.startsWith("e05@0-1320,e01@1320-2640,e03@2640-3960,e04@3960-5280,e02@5280-6600,e05@6600-7642,e03@7642-8962,"), text)
        assertTrue(text.endsWith("e04@85522-86400".replace("e04@85522", "e05@85522")), text)
    }

    @Test fun `blocks are contiguous and cover exactly 24 hours`() {
        val out = packer.pack(DayPackRequest(pool, dayStart, 20000, channelId = 1))
        assertEquals(dayStart, out.first().startEpochSec)
        assertEquals(dayStart + 86_400, out.last().endEpochSec)
        out.zipWithNext().forEach { (a, b) -> assertEquals(a.endEpochSec, b.startEpochSec) }
    }

    @Test fun `empty or zero-length pool gives no blocks`() {
        assertEquals(emptyList(), packer.pack(DayPackRequest(emptyList(), dayStart, 1, 1)))
        assertEquals(emptyList(), packer.pack(DayPackRequest(listOf(MediaItem("z", "Z", 0, MediaType.MOVIE)), dayStart, 1, 1)))
    }
}
